### ISSUE TITLE
quamobrem

### ISSUE THREAD

**Issue by wehro** [gregorio-project/latin-ecclesiastic-accents#14]
Max Niedermann (*Phonétique historique du latin*, Paris 1940, § 103) states: 

> On séparait donc prod-eo, red-arguo, ab-ripio, ob-lino, haru-spex, lecti-sternium et non pro-deo, re-darguo, a-bripio, o-blino, harus-pex, lectis-ternium comme le demanderait le principe général. C'est ce qui nous fait comprendre pourquoi, chez Plaute et chez Térence, la syllabe initiale des verbes composés du type de abripio, oblino vaut toujours longue (p. ex. Plaute, Curc. 695, Poen. 1195, Térence, Andr. 786), bien que, par ailleurs, le groupe occlusive + vibrante ou latérale ne produise jamais d'allongement par position dans la vieille poésie classique.

If this principle also applies to ecclesiastic accents, *quam-ob-rem* should be accentuated *quam-ób-rem* rather than *quám-ob-rem*, because the penultimate is long.

**Comment by BrRoman** [comment]
Dear wehro,
It seems that the principle applies in ecclesiastic latin, since I have found *quamóbrem* in the resources of Divinum-officium. So I will correct it on Accenteur.
Thanks a lot!
