### ISSUE TITLE
cuidam and cuiquam

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/latin-ecclesiastic-accents#21]
In vulgate_with_accents.txt cuidam and cuiquam (which only appear 1 and 3 times respectively) are not marked with any accent.  Cuidam appears in today's (Feria Quinta post Dominicam I Passionis) where it is marked as cuídam, but I found an old Dominican Missal that has it as cúidam [here](https://books.google.com/books?id=Sx5lAAAAcAAJ&pg=PA126&lpg=PA126&dq=c%C3%BAidam&source=bl&ots=Ivboevg0jq&sig=ACfU3U04wVSKqHlCgPxPD0UkfBEV06w79Q&hl=en&sa=X&ved=2ahUKEwiFrqXikMjhAhUFKKwKHeg0DzQQ6AEwAHoECAkQAQ#v=onepage&q=c%C3%BAidam&f=false) and I wasn't sure of the vowel lengths, so I'm not sure which is correct.

**Comment by BrRoman** [comment]
Dear Benjamin,
The most common use is that "-dam" and "-quam" make long the antepenultimate.
Thanks a lot, and have a holy "Hebdomada magna".
Br. Roman Mary
