### ISSUE TITLE
facíei vs faciéi, and other 5th declension nouns

### ISSUE THREAD

**Issue by bbloomf** [gregorio-project/latin-ecclesiastic-accents#6]
I noticed that faciei is given correctly (faciéi) here: https://github.com/gregorio-project/latin-ecclesiastic-accents/blob/master/corpus/psalms/special/030.txt#L24
but incorrectly (facíei) here: https://github.com/gregorio-project/latin-ecclesiastic-accents/blob/master/corpus/psalms/vatican/030%20In%20te%20Domine.txt#L52
Similar mistakes exist in https://github.com/gregorio-project/latin-ecclesiastic-accents/blob/master/corpus/vulgate/vulgate_with_accents.txt

**Comment by BrRoman** [comment]
Thanks for this notice, dear Benjamin.

I've corrected the Vulgate, but concerning the Psalms I'm not sure, as the version is the Nova Vulgata. Perhaps it's another choice the authors have made. Dear Fradec, what do you think about that?

In the Vulgate I've corrected 'faciéi' (Ps 30 and Ps 43) and 'speciéi' (Ps 67). Have you other suggestions?

Yours in Christ.
Br. Roman Mary

**Comment by fradec** [comment]
It mays exist still other errors of this type in the corpus psalms/vatican because the accentuation was automatically realized with Collatinus without a very elaborate proofreading. I'll correct those mistakes.
The psalms/special corpus is more guaranteed for accentuation: it is based on Solesmes' books.

**Comment by BrRoman** [comment]
Dear Fradec,
I've corrected some other mistakes in vatican and inserted your observation in the readme.
This issue is closed (for now!).
