### ISSUE TITLE
accenteur vs. vulgata psalms from liturgical books (Antiphonale Monasticum 1934, Nocturnale Romanum 2002)

### ISSUE THREAD

**Issue by jakubjelinek** [gregorio-project/latin-ecclesiastic-accents#8]
I've completed today accent verification of my psalm collection (essentially, stripped with sed all accents from all psalms concatenated, run that through accenteur/index.html, when it gave me choices or other kinds of red color resolved according to the corresponding liturgical books, then diffed the original I had vs. the newly reaccented and if there were differences, looked up details in the liturgical books and resolved accoring to that.  I'll attach unified diff between what accenteur produced the above way and what I've changed to match the liturgical books, in case it helps.

**Comment by jakubjelinek** [comment]
--- psalmi3.orig	2018-09-16 20:35:11.000000000 +0200
+++ psalmi3	2018-09-18 22:11:00.504027038 +0200
@@ -120,8 +120,8 @@ Qui probátus est in illo, et perféctus
 erit illi glória ætérna.
 Qui pótuit tránsgredi, et non est transgréssus; *
 fácere mala, et non fecit?
-Ideo stabilíta sunt bona íllius in Dómino, *
-et eleemósynas íllius enarrábit omnis ecclésia sanctórum.
+Ideo stabilíta sunt bona illíus in Dómino, *
+et eleemósynas illíus enarrábit omnis ecclésia sanctórum.
 
 Ego dixi: In dimídio diérum meórum, *
 vadam ad portas ínferi.
@@ -452,13 +452,13 @@ et iníquus benedícitur.
 Exacerbávit Dóminum peccátor, *
 secúndum multitúdinem iræ suæ non quæret.
 Non est Deus in conspéctu ejus: *
-inquinátæ sunt viæ íllius in omni témpore.
+inquinátæ sunt viæ illíus in omni témpore.
 Auferúntur judícia tua a fácie ejus: *
 ómnium inimicórum suórum dominábitur.
 Dixit enim in corde suo: *
 Non movébor a generatióne in generatiónem sine malo.
 Cujus maledictióne os plenum est, et amaritúdine, et dolo: *
-sub língua ejus labor et dolor.
+sub lingua ejus labor et dolor.
 Sedet in insídiis cum divítibus in occúltis, *
 ut interfíciat innocéntem.
 Oculi ejus in páuperem respíciunt: *
@@ -479,9 +479,9 @@ ut tradas eos in manus tuas:
 Tibi derelíctus est pauper: *
 órphano tu eris adjútor.
 Cóntere bráchium peccatóris et malígni: *
-quærétur peccátum íllius, et non inveniétur.
+quærétur peccátum illíus, et non inveniétur.
 Dóminus regnábit in ætérnum, et in sǽculum sǽculi: *
-períbitis gentes de terra íllius.
+períbitis gentes de terra illíus.
 Desidérium páuperum exaudívit Dóminus: *
 præparatiónem cordis eórum audívit auris tua.
 Judicáre pupíllo et húmili, *
@@ -511,7 +511,7 @@ aut quis requiéscet in monte sancto tuo
 Qui ingréditur sine mácula, *
 et operátur justítiam:
 Qui lóquitur veritátem in corde suo, *
-qui non egit dolum in língua sua:
+qui non egit dolum in lingua sua:
 Nec fecit próximo suo malum, *
 et oppróbrium non accépit advérsus próximos suos.
 Ad níhilum dedúctus est in conspéctu ejus malígnus: *
@@ -537,7 +537,7 @@ a summo cælo egréssio ejus:
 Et occúrsus ejus usque ad summum ejus: *
 nec est qui se abscóndat a calóre ejus.
 Lex Dómini immaculáta, convértens ánimas: *
-testimónium Dómini fidéle, sapiéntiam prǽstans párvulis.
+testimónium Dómini fidéle, sapiéntiam præstans párvulis.
 Justítiæ Dómini rectæ, lætificántes corda: *
 præcéptum Dómini lúcidum, illúminans óculos.
 Timor Dómini sanctus, pérmanens in sǽculum sǽculi: *
@@ -580,7 +580,7 @@ et semen eórum a fíliis hóminum.
 Quóniam declinavérunt in te mala: *
 cogitavérunt consília, quæ non potuérunt stabilíre.
 Quóniam pones eos dorsum: *
-in reliqúiis tuis præparábis vultum eórum.
+in relíquiis tuis præparábis vultum eórum.
 Exaltáre, Dómine, in virtúte tua: *
 cantábimus et psallémus virtútes tuas.
 
@@ -603,7 +603,7 @@ ómnibus diébus vitæ meæ:
 Et ut inhábitem in domo Dómini; *
 in longitúdinem diérum.
 
-Dómini est terra, et plénitudo ejus, *
+Dómini est terra, et plenitúdo ejus, *
 orbis terrárum, et univérsi, qui hábitant in eo.
 Quia ipse super mária fundávit eum, *
 et super flúmina præparávit eum.
@@ -753,7 +753,7 @@ Annuntiávi et locútus sum: *
 multiplicáti sunt super númerum.
 Sacrifícium et oblatiónem noluísti: *
 aures autem perfecísti mihi.
-Holocaústum et pro peccáto non postulásti: *
+Holocáustum et pro peccáto non postulásti: *
 tunc dixi: Ecce vénio.
 In cápite libri scriptum est de me ut fácerem voluntátem tuam: *
 Deus meus, vólui, et legem tuam in médio cordis mei.
@@ -797,7 +797,7 @@ univérsum stratum ejus versásti in inf
 Ego dixi: Dómine miserére mei: *
 sana ánimam meam, quia peccávi tibi.
 Inimíci mei dixérunt mala mihi: *
-Quándo moriétur, et períbit nomen ejus?
+Quando moriétur, et períbit nomen ejus?
 Et si ingrediebátur ut vidéret, vana loquebátur: *
 cor ejus congregávit iniquitátem sibi.
 Egrediebátur foras, *
@@ -855,7 +855,7 @@ salutáre vultus mei, et Deus meus.
 
 Eructávit cor meum verbum bonum, *
 dico ego ópera mea Regi.
-Língua mea, cálamus scribæ *
+Lingua mea, cálamus scribæ *
 velóciter scribéntis.
 Speciósus forma præ fíliis hóminum, diffúsa est grátia in lábiis tuis, *
 proptérea benedíxit te Deus in ætérnum.
@@ -996,16 +996,16 @@ et spíritu principáli confírma me.
 Docébo iníquos vias tuas: *
 et ímpii ad te converténtur.
 Líbera me de sanguínibus Deus, Deus salútis meæ: *
-et exsultábit língua mea justítiam tuam.
+et exsultábit lingua mea justítiam tuam.
 Dómine lábia mea apéries: *
 et os meum annuntiábit laudem tuam.
 Quóniam si voluísses sacrifícium, dedíssem útique: *
-holocaústis non delectáberis.
+holocáustis non delectáberis.
 Sacrifícium Deo spíritus contribulátus: *
 cor contrítum et humiliátum Deus non despícies.
 Benígne fac Dómine in bona voluntáte tua Sion: *
 ut ædificéntur muri Jerúsalem.
-Tunc acceptábis sacrifícium justítiæ, oblatiónes et holocaústa: *
+Tunc acceptábis sacrifícium justítiæ, oblatiónes et holocáusta: *
 tunc impónent super altáre tuum vítulos.
 
 Deus, in nómine tuo salvum me fac: *
@@ -1054,7 +1054,7 @@ Exáudi Deus oratiónem meam cum déprec
 a timóre inimíci éripe ánimam meam.
 Protexísti me a convéntu malignántium, *
 a multitúdine operántium iniquitátem.
-Quia exacuérunt ut gládium línguas suas: +
+Quia exacuérunt ut gládium linguas suas: +
 intendérunt arcum rem amáram, *
 ut sagíttent in occúltis immaculátum.
 Súbito sagittábunt eum, et non timébunt: *
@@ -1066,7 +1066,7 @@ defecérunt scrutántes scrutínio.
 Accédet homo ad cor altum: *
 et exaltábitur Deus.
 Sagíttæ parvulórum factæ sunt plagæ eórum: *
-et infirmátæ sunt contra eos línguæ eórum.
+et infirmátæ sunt contra eos linguæ eórum.
 Conturbáti sunt omnes qui vidébant eos: *
 et tímuit omnis homo.
 Et annuntiavérunt ópera Dei, *
@@ -1131,16 +1131,16 @@ posuísti tribulatiónes in dorso nostro
 imposuísti hómines super cápita nostra.
 Transívimus per ignem et aquam, *
 et eduxísti nos in refrigérium.
-Introíbo in domum tuam in holocaústis; *
+Introíbo in domum tuam in holocáustis; *
 reddam tibi vota mea, quæ distinxérunt lábia mea.
 Et locútum est os meum *
 in tribulatióne mea.
-Holocaústa medulláta ófferam tibi cum incénso aríetum: *
+Holocáusta medulláta ófferam tibi cum incénso aríetum: *
 ófferam tibi boves cum hircis.
 Veníte, audíte, et narrábo, omnes, qui timétis Deum: *
 quanta fecit ánimæ meæ.
 Ad ipsum ore meo clamávi, *
-et exaltávi sub língua mea.
+et exaltávi sub lingua mea.
 Iniquitátem si aspéxi in corde meo, *
 non exáudiet Dóminus.
 Proptérea exaudívit Deus, *
@@ -1177,12 +1177,12 @@ Exsultáte in conspéctu ejus: +
 turbabúntur a fácie ejus, *
 patris orphanórum, et júdicis viduárum.
 Deus in loco sancto suo: *
-Deus qui inhabitáre facit únius moris in domo:
+Deus qui inhabitáre facit uníus moris in domo:
 Qui edúcit vinctos in fortitúdine, *
 simíliter eos, qui exásperant, qui hábitant in sepúlchris.
 Deus, cum egrederéris in conspéctu pópuli tui, *
 cum pertransíres in desérto:
+Terra mota est, étenim cœli distillavérunt a fácie Dei Sínai, *
-Terra mota est, étenim cœ́li distillavérunt a fácie Dei Sínai, *
 a fácie Dei Israël.
 Plúviam voluntáriam segregábis Deus hæreditáti tuæ: et infirmáta est, *
 tu vero perfecísti eam.
@@ -1216,7 +1216,7 @@ Benedíctus Dóminus die quotídie: *
 Dixit Dóminus: Ex Basan convértam, *
 convértam in profúndum maris:
 Ut intingátur pes tuus in sánguine: *
-língua canum tuórum ex inimícis, ab ipso.
+lingua canum tuórum ex inimícis, ab ipso.
 Vidérunt ingréssus tuos Deus, +
 ingréssus Dei mei: *
 Regis mei qui est in sancto.
@@ -1240,7 +1240,7 @@ vénient legáti ex Ægýpto: *
 Æthiópia prævéniet manus ejus Deo.
 Regna terræ, cantáte Deo: *
 psállite Dómino.
-Psállite Deo, qui ascéndit super cœ́lum cœ́li, *
+Psállite Deo, qui ascéndit super cœlum cœli, *
 ad Oriéntem.
 Ecce dabit voci suæ vocem virtútis, +
 date glóriam Deo super Israël, *
@@ -1315,7 +1315,7 @@ cantábo Deo Jacob.
 Et ómnia córnua peccatórum confríngam: *
 et exaltabúntur córnua justi.
 
-Benedixísti, Dómine, terram tuam: *
+Benedíxisti, Dómine, terram tuam: *
 avertísti captivitátem Jacob.
 Remisísti iniquitátem plebis tuæ: *
 operuísti ómnia peccáta eórum.
@@ -1329,7 +1329,7 @@ Deus tu convérsus vivificábis nos: *
 et plebs tua lætábitur in te.
 Osténde nobis, Dómine, misericórdiam tuam: *
 et salutáre tuum da nobis.
-Audíam quid loquátur in me Dóminus Deus: *
+Audiam quid loquátur in me Dóminus Deus: *
 quóniam loquétur pacem in plebem suam.
 Et super sanctos suos: *
 et in eos qui convertúntur ad cor.
@@ -1478,7 +1478,7 @@ a vócibus aquárum multárum.
 Mirábiles elatiónes maris: *
 mirábilis in altis Dóminus.
 Testimónia tua credibília facta sunt nimis: *
-domum tuam decet sánctitudo Dómine in longitúdinem diérum.
+domum tuam decet sanctitúdo Dómine in longitúdinem diérum.
 
 Cantáte Dómino cánticum novum, *
 cantáte Dómino omnis terra.
@@ -1502,7 +1502,7 @@ dícite in Géntibus quia Dóminus regn�
 Etenim corréxit orbem terræ, qui non commovébitur, *
 judicábit pópulos in æquitáte.
 Læténtur cæli, et exsúltet terra, +
-commoveátur mare, et plénitudo ejus: *
+commoveátur mare, et plenitúdo ejus: *
 gaudébunt campi, et ómnia, quæ in eis sunt.
 Tunc exaltábunt ómnia ligna silvárum a fácie Dómini, quia venit: *
 quóniam venit judicáre terram.
@@ -1551,7 +1551,7 @@ Jubiláte Deo omnis terra, *
 cantáte, et exsultáte, et psállite.
 Psállite Dómino in cíthara, in cíthara et voce psalmi, *
 in tubis ductílibus, et voce tubæ córneæ.
-Jubiláte in conspéctu Regis Dómini, moveátur mare, et plénitudo ejus, *
+Jubiláte in conspéctu Regis Dómini, moveátur mare, et plenitúdo ejus, *
 orbis terrárum, et qui hábitant in eo.
 Flúmina plaudent manu, simul montes exsultábunt a conspéctu Dómini; *
 quóniam venit judicáre terram.
@@ -1575,7 +1575,7 @@ Bénedic ánima mea Dómino: *
 Dómine Deus meus magnificátus es veheménter.
 Confessiónem, et decórem induísti: *
 amíctus lúmine sicut vestiménto:
-Exténdens cœ́lum sicut pellem: *
+Exténdens cœlum sicut pellem: *
 qui tegis aquis superióra ejus.
 Qui ponis nubem ascénsum tuum: *
 qui ámbulas super pennas ventórum.
@@ -1595,7 +1595,7 @@ Qui emíttis fontes in convállibus: *
 inter médium móntium pertransíbunt aquæ.
 Potábunt omnes béstiæ agri: *
 exspectábunt ónagri in siti sua.
-Super ea vólucres cœ́li habitábunt: *
+Super ea vólucres cœli habitábunt: *
 de médio petrárum dabunt voces.
 Rigans montes de superióribus suis: *
 de fructu óperum tuórum satiábitur terra:
@@ -1698,7 +1698,7 @@ dispónet sermónes suos in judício: *
 quia in ætérnum non commovébitur.
 In memória ætérna erit justus: *
 ab auditióne mala non timébit.
-Páratum cor ejus speráre in Dómino +
+Parátum cor ejus speráre in Dómino +
 confirmátum est cor ejus: *
 non commovébitur donec despíciat inimícos suos.
 Dispérsit, dedit paupéribus: +
@@ -2010,7 +2012,7 @@ Deprecátus sum fáciem tuam in toto cor
 miserére mei secúndum elóquium tuum.
 Cogitávi vias meas: *
 et convérti pedes meos in testimónia tua.
-Páratus sum, et non sum turbátus: *
+Parátus sum, et non sum turbátus: *
 ut custódiam mandáta tua.
 Funes peccatórum circumpléxi sunt me: *
 et legem tuam non sum oblítus.
@@ -2027,7 +2029,7 @@ Deprecátus sum fáciem tuam in toto cor
 miserére mei secúndum elóquium tuum.
 Cogitávi vias meas: *
 et convérti pedes meos in testimónia tua.
-Páratus sum, et non sum turbátus: *
+Parátus sum, et non sum turbátus: *
 ut custódiam mandáta tua.
 Funes peccatórum circumpléxi sunt me: *
 et legem tuam non sum oblítus.
@@ -2111,7 +2113,7 @@ Deprecátus sum fáciem tuam in toto cor
 miserére mei secúndum elóquium tuum.
 Cogitávi vias meas: *
 et convérti pedes meos in testimónia tua.
-Páratus sum, et non sum turbátus: *
+Parátus sum, et non sum turbátus: *
 ut custódiam mandáta tua.
 Funes peccatórum circumpléxi sunt me: *
 et legem tuam non sum oblítus.
@@ -2295,7 +2297,7 @@ Deprecátus sum fáciem tuam in toto cor
 miserére mei secúndum elóquium tuum.
 Cogitávi vias meas: *
 et convérti pedes meos in testimónia tua.
-Páratus sum, et non sum turbátus: *
+Parátus sum, et non sum turbátus: *
 ut custódiam mandáta tua.
 Funes peccatórum circumpléxi sunt me: *
 et legem tuam non sum oblítus.
@@ -2409,7 +2411,7 @@ latum mandátum tuum nimis.
 Defécit in salutáre tuum ánima mea: *
 et in verbum tuum supersperávi.
 Defecérunt óculi mei in elóquium tuum, *
-dicéntes: Quándo consoláberis me?
+dicéntes: Quando consoláberis me?
 Quia factus sum sicut uter in pruína: *
 justificatiónes tuas non sum oblítus.
 Quot sunt dies servi tui? *
@@ -2426,7 +2428,7 @@ et custódiam testimónia oris tui.
 Defécit in salutáre tuum ánima mea: *
 et in verbum tuum supersperávi.
 Defecérunt óculi mei in elóquium tuum, *
-dicéntes: Quándo consoláberis me?
+dicéntes: Quando consoláberis me?
 Quia factus sum sicut uter in pruína: *
 justificatiónes tuas non sum oblítus.
 Quot sunt dies servi tui? *
@@ -2477,7 +2479,7 @@ proptérea odívi omnem viam iniquitáti
 Defécit in salutáre tuum ánima mea: *
 et in verbum tuum supersperávi.
 Defecérunt óculi mei in elóquium tuum, *
-dicéntes: Quándo consoláberis me?
+dicéntes: Quando consoláberis me?
 Quia factus sum sicut uter in pruína: *
 justificatiónes tuas non sum oblítus.
 Quot sunt dies servi tui? *
@@ -2510,7 +2512,7 @@ latum mandátum tuum nimis.
 Defécit in salutáre tuum ánima mea: *
 et in verbum tuum supersperávi.
 Defecérunt óculi mei in elóquium tuum, *
-dicéntes: Quándo consoláberis me?
+dicéntes: Quando consoláberis me?
 Quia factus sum sicut uter in pruína: *
 justificatiónes tuas non sum oblítus.
 Quot sunt dies servi tui? *
@@ -2777,7 +2779,7 @@ Intret postulátio mea in conspéctu tuo
 secúndum elóquium tuum éripe me.
 Eructábunt lábia mea hymnum, *
 cum docúeris me justificatiónes tuas.
-Pronuntiábit língua mea elóquium tuum: *
+Pronuntiábit lingua mea elóquium tuum: *
 quia ómnia mandáta tua ǽquitas.
 Fiat manus tua ut salvet me: *
 quóniam mandáta tua elégi.
@@ -2843,7 +2845,7 @@ Intret postulátio mea in conspéctu tuo
 secúndum elóquium tuum éripe me.
 Eructábunt lábia mea hymnum, *
 cum docúeris me justificatiónes tuas.
-Pronuntiábit língua mea elóquium tuum: *
+Pronuntiábit lingua mea elóquium tuum: *
 quia ómnia mandáta tua ǽquitas.
 Fiat manus tua ut salvet me: *
 quóniam mandáta tua elégi.
@@ -2857,9 +2859,9 @@ quære servum tuum, quia mandáta tua no
 Ad Dóminum cum tribulárer clamávi: *
 et exaudívit me.
 Dómine líbera ánimam meam a lábiis iníquis, *
-et a língua dolósa.
+et a lingua dolósa.
 Quid detur tibi, aut quid apponátur tibi *
-ad línguam dolósam?
+ad linguam dolósam?
 Sagíttæ poténtis acútæ, *
 cum carbónibus desolatóriis.
 Heu mihi, quia incolátus meus prolongátus est: +
@@ -2947,13 +2949,13 @@ pax super Israel.
 In converténdo Dóminus captivitátem Sion: *
 facti sumus sicut consoláti.
 Tunc replétum est gáudio os nostrum: *
-et língua nostra exsultatióne.
+et lingua nostra exsultatióne.
 Tunc dicent inter gentes: *
 Magnificávit Dóminus fácere cum eis.
 Magnificávit Dóminus fácere nobíscum: *
 facti sumus lætántes.
 Convérte Dómine captivitátem nostram, *
-sicut torrens in Aústro.
+sicut torrens in Austro.
 Qui séminant in lácrimis, *
 in exsultatióne metent.
 Eúntes ibant et flebant, *
@@ -3090,7 +3093,7 @@ intérroga me, et cognósce sémitas mea
 Intellexísti cogitatiónes meas de longe: *
 sémitam meam et funículum meum  investigásti.
 Et omnes vias meas prævidísti: *
-quia non est sermo in língua mea.
+quia non est sermo in lingua mea.
 Ecce Dómine tu cognovísti ómnia novíssima et antíqua: *
 tu formásti me, et posuísti super me manum tuam.
 Mirábilis facta est sciéntia tua ex me: *
@@ -3116,7 +3120,7 @@ tu cognovísti sessiónem meam et resurr
 Intellexísti cogitatiónes meas de longe: *
 sémitam meam et funículum meum investigásti.
 Et omnes vias meas prævidísti: *
-quia non est sermo in língua mea.
+quia non est sermo in lingua mea.
 Ecce Dómine tu cognovísti ómnia novíssima et antíqua: *
 tu formásti me, et posuísti super me manum tuam.
 Mirábilis facta est sciéntia tua ex me: *
@@ -3165,7 +3169,7 @@ Eripe me Dómine ab hómine malo: *
 a viro iníquo éripe me.
 Qui cogitavérunt iniquitátes in corde: *
 tota die constituébant prœ́lia.
-Acuérunt línguas suas sicut serpéntis: *
+Acuérunt linguas suas sicut serpéntis: *
 venénum áspidum sub lábiis eórum.
 Custódi me Dómine de manu peccatóris: *
 et ab homínibus iníquis éripe me.
@@ -3244,7 +3249,7 @@ quia confortáti sunt super me.
 Et érue me de manu filiórum alienórum, +
 quorum os locútum est vanitátem: *
 et déxtera eórum, déxtera iniquitátis:
-Quórum fílii, sicut novéllæ plantatiónes *
+Quorum fílii, sicut novéllæ plantatiónes *
 in juventúte sua.
 Fíliæ eórum compósitæ: *
 circumornátæ ut similitúdo templi.
@@ -3273,7 +3279,7 @@ emítte sagíttas tuas, et conturbábis
 Emítte manum tuam de alto, +
 éripe me, et líbera me de aquis multis: *
 de manu filiórum alienórum.
-Quórum os locútum est vanitátem: *
+Quorum os locútum est vanitátem: *
 et déxtera eórum, déxtera iniquitátis.
 
 Confiteántur tibi Dómine ómnia ópera tua: *
@@ -3457,7 +3468,7 @@ Reges terræ et omnes pópuli: *
 príncipes et omnes júdices terræ.
 Júvenes et vírgines: +
 senes cum junióribus laudent nomen Dómini: *
-quia exaltátum est nomen ejus sólius.
+quia exaltátum est nomen ejus solíus.
 Conféssio ejus super cælum et terram: *
 et exaltávit cornu pópuli sui.
 Hymnus ómnibus sanctis ejus: *

**Comment by BrRoman** [comment]
Dear Jakub,

Sorry for the delay of this answer. I just come back from (wonderful) holidays in the Alps, where I had no access to internet or e-mails.
Thanks a lot for your outstanding work. I'll look at it more accurately as soon as possible, but I can already say to you that yes, "it will help"!
Have you the last version of Accenteur? I thought I had treated the words like illius, ipsius etc., but perhaps I have forgotten to push that on Github.
Now, essentially it seems that the next step is to manage the words with "gu" and "qu".

Yours in Christ.
Br. Roman

**Comment by jakubjelinek** [comment]
I've done a git pull now and indeed, some words got fixed, e.g.
illius quando audiam paratum paratus quorum solius
now show up correctly as
illíus quando áudiam parátum parátus quorum solíus
Other words still don't work properly:
quæsumus
is not recognized at all,
præsta lingua præstans plenitudo holocaustum unius cœlum cœli sanctitudo Austro
are accented as
praésta língua praéstans plénitudo holocaústum únius cœ́lum cœ́li sánctitudo Aústro
rather than
præsta lingua præstans plenitúdo holocáustum uníus cœlum cœli sanctitúdo Austro
The weirdest is plenitudo and sanctitudo, where the accent is put on the first of 4 syllables, which should be impossible (must be second to last or third to last).

From the usability POV, it would be nice if for the words where there are two possibilities of accent one could make a choice once for all such words in the text, e.g. in the psalms there are hundreds of occurrences of Domine where one wants to use Dómine all the time, never Domíne.

Thanks

**Comment by BrRoman** [comment]
Dear Jakub,

Thanks for your feedback. I have beginned to make the corrections on local (unius, lingua and quaesumus are fixed).
Have you an idea of how to realize - in practice - the "choice one for all"? I think it's a very good idea, but I hardly figure out how to "draw" that graphically. If you had an example from another site, it would help me.

Yours in Christ.

-- 
+ Gloire à Dieu +
Fr. Romain Marie
Abbaye Saint-Joseph
21150 Flavigny-sur-Ozerain
03 80 96 22 31
http://clairval.com
Services <http://services.asj.com> (intranet)

**Comment by jakubjelinek** [comment]
On Wed, Sep 26, 2018 at 03:24:26PM +0000, Brother Roman wrote:
> Thanks for your feedback. I have beginned to make the corrections on local (unius, lingua and quaesumus are fixed).

Thanks.

> Have you an idea of how to realize - in practice - the "choice one for
> all"?  I think it's a very good idea, but I hardly figure out how to
> "draw" that graphically.  If you had an example from another site, it
> would help me.

I'm used to e.g. aspell (http://aspell.net/) interactive spellchecking,
where one problematic word is highlighted at a time and the user has a
choice of various actions, changing it to one of the offered spellings,
remembering in some local dictionary, ignoring etc.

Another thing I ran into is that at least the demo accenteur web interface
requires one to strip all the accents from the text first (which can be done
easily e.g. with sed, sure), maybe it would be useful to work also on
previously accented words, do nothing if the accent is correct, use some way
to mark errors when there is accent that shouldn't be there or is on an
incorrect syllable.  That way one could easily use accenteur to just verify
if the accents are correct.

	Jakub

**Comment by BrRoman** [comment]
OK, I'll open 2 new issues, to divide the problems.
Br. Roman

**Comment by BrRoman** [comment]
Dear Jakub,

I have treated the problematic words that you had mentioned to me.
As I have largely amended the code, it's possible that it causes other unintended effects. So could you please make new tests on the Psalms (or other liturgical texts)?

On the other hand, I have opened 2 new issues for your suggestions of improvement for Accenteur.

Yours in Christ.
Br. Roman Mary
